### ISSUE TITLE
how import this

### ISSUE THREAD

**Issue by njacob1001** [bbottema/js-epub-maker#4]
Hello, How can I import this library? y tried with import or require but doesn't
 work.

**Comment by bbottema** [comment]
It's not modules or typescript (yet), so options are limited. A conversion to a properly modularized library is planned for the future but not anytime soon.

However, I included a working demo, which demonstrates how to load the project. Please check the readme.

**Comment by dr-nyt** [comment]
Is it not possible to get an epubmaker.min.js so we can directly load it into the HTML?

**Comment by bbottema** [comment]
> Is it not possible to get an epubmaker.min.js so we can directly load it into the HTML?

It's already there in the [dist](https://github.com/bbottema/js-epub-maker/tree/master/dist) folder.
